kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "global.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
data:
  {{- $root := . }}
  {{- range $path, $_ := .Files.Glob "resources/**" }}
  {{ base $path }}: |
    {{- tpl ($root.Files.Get $path) $root | nindent 4 }}
  {{- end }}