{{- $dot := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "egress.fullname" . }}
  labels:
    {{- include "egress.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range $index, $val := .Values.routers }}
    - name: {{ $val.name }}-port
      port: {{ add 8080 $index }}
      targetPort: {{ $val.name }}-port
      protocol: TCP
    {{- end }}
  selector:
    {{- include "egress.selectorLabels" . | nindent 4 }}
{{- range .Values.routers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
  labels:
    {{- include "egress.labels" $dot | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .name }}-port
      protocol: TCP
  selector:
    {{- include "egress.selectorLabels" $dot | nindent 4 }}
{{- end }}