{{- if .Values.insight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insight.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insight.labels" . | nindent 4 }}
spec:
  {{- if not .Values.insight.autoscaling.enabled }}
  replicas: {{ .Values.insight.autoscaling.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "insight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "insight.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis-insight
          image: "{{ .Values.insight.image.repository }}:{{ .Values.insight.image.tag }}"
          imagePullPolicy: {{ .Values.insight.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          resources:
            {{- toYaml .Values.insight.resources | nindent 12 }}
      {{- with .Values.insight.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.insight.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.insight.affinity }}
      {{- with .Values.insight.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      affinity:
        # 让副本分布到不同的节点上，避免单点故障
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values: ["redis-insight"]
                    - key: "app.kubernetes.io/instance"
                      operator: In
                      values: [{{ .Release.Name | quote }}]
      {{- end }}
{{- end }}