{{- if .Values.insight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insight.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insight.labels" . | nindent 4 }}
spec:
  {{- if .Values.maintenance }}
  replicas: 0
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "insight.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "insight.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis-insight
          image: "{{ .Values.insight.image.repository }}:{{ .Values.insight.image.tag }}"
          imagePullPolicy: {{ .Values.insight.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          env:
            - name: RITRUSTEDORIGINS
              value: {{ .Values.insight.conf.trustedOrigins | quote }}
            {{- if .Values.insight.conf.subpath }}
            - name: RIPROXYPATH
              value: {{ .Values.insight.conf.subpath | quote }}
            {{- end }}
            - name: RIPROXYPREFIX
              value: "X-Forwarded-Prefix"
          resources:
            {{- toYaml .Values.insight.resources | nindent 12 }}
          startupProbe:
            httpGet:
              port: http
              path: /api/config/
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              port: http
              path: /api/config/
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      {{- with .Values.insight.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.insight.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.insight.affinity }}
      {{- with .Values.insight.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      affinity:
        # 让 Pod 只调度到对应命名空间的节点上，保证生产环境和预发布环境节点隔离
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/namespace
                    operator: In
                    values: [{{ .Release.Namespace | quote }}]
      {{- end }}
{{- end }}