{{- if .Values.insight.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insight.name" . }}
  labels:
    {{- include "insight.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "insight.selectorLabels" . | nindent 4 }}
{{- end }}