{{- $conf := mustMergeOverwrite (dict) (deepCopy .Values.global) (deepCopy .Values.multicast) -}}
{{- if $conf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multicast.name" . }}
  labels:
    {{- include "multicast.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "multicast.selectorLabels" . | nindent 4 }}
{{- end }}