apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexus.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.pvc | nindent 2 }}