apiVersion: v1
kind: Service
metadata:
  name: {{ include "global.name" . }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    {{- range $it := .Values.service.ports }}
    - name: {{ $it.name }}
      port: {{ $it.port }}
      targetPort: {{ $it.name }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "global.selectorLabels" . | nindent 4 }}
