kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  {{- with .Values.cnf }}
  {{- toYaml . | nindent 2 }}
  {{- end }}