kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  {{- with .Values.conf }}
  {{- toYaml . | nindent 2 }}
  {{- end }}