kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mysql.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  {{- $root := . }}
  {{- range $path, $_ := .Files.Glob "resources/mysql/conf.d/**" }}
  {{ base $path }}: |
    {{- tpl ($root.Files.Get $path) $root | nindent 4 }}
  {{- end }}