apiVersion: v1
kind: Service
metadata:
  name: pinpoint-mysql
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: socket
      port: 3306
      targetPort: socket
      protocol: TCP
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}