# 镜像
image:
  registry: docker.io
  repository: adolfintel/speedtest
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# 应用资源限制
resources:
  limits:
    cpu: 4000m
  requests:
    cpu: 100m

# 自动横向拓展
autoscaling:
  # 是否启用横向拓展，如果不启用，则默认启动 minReplicas 个副本
  enabled: false
  # 最小副本数量
  minReplicas: 1
  # 最大副本数量
  maxReplicas: 5
  # CPU 超过 resource.limits.cpu 里面限制的 60% 就触发横向拓展
  targetCPUPercentage: 60

# 节点选择器
nodeSelector: {}
# 污点容忍度
tolerations: []
# 亲和性，如果为空时，默认的亲和性尽量将同一应用的 Pod 分布到不同的节点上
# 如果不为空时，以用户的亲和性为准
affinity: {}

# 流量入口
ingress:
  enabled: true
  className: "nginx"
  # 部署后，如果未指定 host，则默认监听 speedtest.${namespace}.cluster.k8s
  #host: speedtest.cluster.k8