kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
data:
  {{- with .Values.global.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}