kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "global.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
data:
  {{- with .Values.global.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}