apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "global.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.global.pvc | nindent 2 }}