apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.global.pvc | nindent 2 }}