# 镜像
image:
  repository: cnk3x/xunlei
  pullPolicy: Always

# 应用资源限制
resources:
  limits:
    cpu: 4000m
    # memory: 8Gi

# 存储配置
pvc:
  storageClassName: permanent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi

# 节点选择器
nodeSelector: {}
# 污点容忍度
tolerations: []
# 亲和性，如果为空时，默认的亲和性尽量将同一应用的 Pod 分布到不同的节点上
# 如果不为空时，以用户的亲和性为准
affinity: {}

# 流量入口
ingress:
  enabled: true
  className: "nginx"
  # 部署后，如果未指定 host，则默认监听 xunlei.${namespace}.cluster.k8s
  # host: xunlei.cluster.k8s
  #deployHost: deploy.xunlei.cluster.k8s