# 镜像
image:
  registry: docker.io
  repository: sonatype/nexus3
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# 应用资源限制
resources:
  limits:
    cpu: 4000m
  requests:
    cpu: 1000m

# 网络配置
service:
  # 暴露其它端口
  ports:
    # 示例，暴露 Docker 镜像仓库端口
    - name: docker-port
      port: 5000

# 流量入口
ingress:
  enabled: true
  annotations: {}
  className: "nginx"
  # 部署后，如果未指定 host，则默认监听 nexus3.<namespace>.cluster.k8s
  # nexus3.<namespace>.cluster.k8s 域名的流量将会转发到 nexus3 的首面
  host:
  # 示例，监听 Docker 镜像仓库端口
  rules:
    - host: docker.pre.cluster.k8s
      paths:
        - path: /v2
          target: docker-port


# 存储配置
pvc:
  storageClassName: permanent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

# 节点选择器
nodeSelector: { }
# 污点容忍度
tolerations: [ ]
# 亲和性，如果为空时，默认的亲和性尽量将同一应用的 Pod 分布到不同的节点上
# 如果不为空时，以用户的亲和性为准
affinity: { }