apiVersion: v1
kind: Service
metadata:
  name: pinpoint-flink-taskmanager
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
    - name: rpc
      port: 6123
      targetPort: rpc
      protocol: TCP
    - name: blob-server
      port: 6124
      targetPort: blob-server
      protocol: TCP
    - name: query-server
      port: 6125
      targetPort: query-server
      protocol: TCP
    - name: flink
      port: 19994
      targetPort: flink
      protocol: TCP
  selector:
    {{- include "taskmanager.selectorLabels" . | nindent 4 }}