{{- if .Values.cloudbeaver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudbeaver.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudbeaver.labels" . | nindent 4 }}
spec:
  {{- if .Values.maintenance }}
  replicas: 0
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloudbeaver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudbeaver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cloudbeaver
          image: "{{ .Values.cloudbeaver.image.repository }}:{{ .Values.cloudbeaver.image.tag }}"
          imagePullPolicy: {{ .Values.cloudbeaver.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8978
              protocol: TCP
          volumeMounts:
            - name: data-volume
              mountPath: /opt/cloudbeaver/workspace
              subPath: cloudbeaver
          resources:
            {{- toYaml .Values.cloudbeaver.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /icons/logo.svg
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /icons/logo.svg
              port: http
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      {{- with .Values.cloudbeaver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cloudbeaver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cloudbeaver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "global.name" . }}

{{- end }}