{{- if and .Values.cloudbeaver.enabled .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-cloudbeaver
  labels:
    {{- include "cloudbeaver.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloudbeaver.selectorLabels" . | nindent 4 }}
{{- end }}