{{- if and .Values.cloudbeaver.enabled .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudbeaver.name" . }}
  labels:
    {{- include "cloudbeaver.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloudbeaver.selectorLabels" . | nindent 4 }}
{{- end }}