apiVersion: v1
kind: Service
metadata:
  name: pinpoint-collector
  labels:
    {{- include "collector.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    # http
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
    # grpc
    - name: grpc-agent
      port: 9991
      targetPort: grpc-agent
      protocol: TCP
    - name: grpc-stat
      port: 9992
      protocol: TCP
      targetPort: grpc-stat
    - name: grpc-span
      port: 9993
      targetPort: grpc-span
      protocol: TCP
    # thrift
    - name: base-port
      port: 9994
      targetPort: base-port
      protocol: TCP
    - name: stat-tcp-port
      port: 9995
      targetPort: stat-tcp-port
      protocol: TCP
    - name: stat-udp-port
      port: 9995
      targetPort: stat-udp-port
      protocol: UDP
    - name: span-tcp-port
      port: 9996
      targetPort: span-tcp-port
      protocol: TCP
    - name: span-udp-port
      port: 9996
      targetPort: span-udp-port
      protocol: UDP
  selector:
    {{- include "collector.selectorLabels" . | nindent 4 }}