kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "batch.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  pinpoint-batch.properties: |
    aa=bb