apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "batch.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "batch.labels" . | nindent 4 }}
spec:
  {{- if .Values.maintenance }}
  replicas: 0
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "batch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "batch.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: waitfor-mysql
          image: "centralx/waitfor:latest"
          imagePullPolicy: Always
          args:
            - "tcp"
            - "pinpoint-mysql"
            - "3306"
        - name: waitfor-zookeeper
          image: "centralx/waitfor:latest"
          imagePullPolicy: Always
          args:
            - "tcp"
            - "pinpoint-zookeeper"
            - "2181"
        - name: waitfor-hbase
          image: "centralx/waitfor:latest"
          imagePullPolicy: Always
          args:
            - "tcp"
            - "pinpoint-hbase"
            - "16000"
      containers:
        - name: batch
          image: "{{ .Values.batch.image.repository }}:{{ .Values.batch.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.batch.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          resources:
            {{- toYaml .Values.batch.resources | nindent 12 }}
{{/*          startupProbe:*/}}
{{/*            httpGet:*/}}
{{/*              port: http*/}}
{{/*              path: /*/}}
{{/*            initialDelaySeconds: 30*/}}
{{/*            timeoutSeconds: 5*/}}
{{/*            periodSeconds: 5*/}}
{{/*            failureThreshold: 20*/}}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              port: http*/}}
{{/*              path: /*/}}
{{/*            timeoutSeconds: 5*/}}
{{/*            periodSeconds: 10*/}}
{{/*            successThreshold: 1*/}}
{{/*            failureThreshold: 3*/}}
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: BATCH_SERVER_PORT
              value: "8079"
            - name: SPRING_PROFILES_ACTIVE
              value: "release"
            - name: PINPOINT_ZOOKEEPER_ADDRESS
              value: "pinpoint-zookeeper"
            - name: CLUSTER_ENABLE
              value: "true"
            - name: ADMIN_PASSWORD
              value: "{{ .Values.batch.config.admin.password }}"
            - name: CONFIG_SENDUSAGE
              value: "false"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
            - name: CONFIG_SHOW_APPLICATIONSTAT
              value: "true"
            - name: BATCH_FLINK_SERVER
              value: "pinpoint-flink-jobmanager"
            - name: JDBC_DRIVERCLASSNAME
              value: "{{ .Values.batch.config.jdbc.driverClassName }}"
            - name: JDBC_URL
              value: "{{ .Values.batch.config.jdbc.url }}"
            - name: JDBC_USERNAME
              value: "{{ .Values.batch.config.jdbc.username | default "root" }}"
            - name: JDBC_PASSWORD
              value: "{{ .Values.batch.config.jdbc.password | default .Values.mysql.config.password }}"
            - name: ALARM_MAIL_SERVER_URL
              value: "{{ .Values.batch.config.alertMail.server.url }}"
            - name: ALARM_MAIL_SERVER_PORT
              value: "{{ .Values.batch.config.alertMail.server.port }}"
            - name: ALARM_MAIL_SERVER_USERNAME
              value: "{{ .Values.batch.config.alertMail.server.username }}"
            - name: ALARM_MAIL_SERVER_PASSWORD
              value: "{{ .Values.batch.config.alertMail.server.password }}"
            - name: ALARM_MAIL_SMTP_SSL_ENABLE
              value: {{ .Values.batch.config.alertMail.smtp.ssl.enable | quote}}
            - name: ALARM_MAIL_SENDER_ADDRESS
              value: "{{ .Values.batch.config.alertMail.senderAddress }}"
            - name: ALARM_MAIL_TRANSPORT_PROTOCOL
              value: "{{ .Values.batch.config.alertMail.transportProtocol }}"
            - name: ALARM_MAIL_SMTP_PORT
              value: "{{ .Values.batch.config.alertMail.smtp.port }}"
            - name: ALARM_MAIL_SMTP_AUTH
              value: "{{ .Values.batch.config.alertMail.smtp.auth }}"
            - name: ALARM_MAIL_SMTP_STARTTLS_ENABLE
              value: "{{ .Values.batch.config.alertMail.smtp.starttls.enable }}"
            - name: ALARM_MAIL_SMTP_STARTTLS_REQUIRED
              value: "{{ .Values.batch.config.alertMail.smtp.starttls.required }}"
            - name: ALARM_MAIL_DEBUG
              value: "{{ .Values.batch.config.alertMail.debug }}"
          volumeMounts:
            - name: config-volume
              mountPath: /pinpoint/config
      {{- with .Values.batch.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.batch.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.batch.affinity }}
      {{- with .Values.batch.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      affinity:
        # 让 Pod 只调度到对应命名空间的节点上，保证生产环境和预发布环境节点隔离
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/namespace
                    operator: In
                    values: [{{ .Release.Namespace | quote }}]
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "batch.name" . }}