apiVersion: v1
kind: Service
metadata:
  name: pinpoint-batch
  labels:
    {{- include "collector.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
  selector:
    {{- include "collector.selectorLabels" . | nindent 4 }}