apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.name" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3306
      targetPort: http
      protocol: TCP
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
