apiVersion: v1
kind: Service
metadata:
  name: pinpoint-zookeeper
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: client-port
      port: 2181
      targetPort: client-port
      protocol: TCP
    - name: tls-port
      port: 3181
      targetPort: tls-port
      protocol: TCP
    - name: follower-port
      port: 2888
      targetPort: follower-port
      protocol: TCP
    - name: election-port
      port: 3888
      targetPort: election-port
      protocol: TCP
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}