# Nacos 集群实例相互访问
apiVersion: v1
kind: Service
metadata:
  name: pinpoint-zookeeper-headless
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client-port
      port: 2181
      targetPort: client-port
    - name: tls-port
      port: 3181
      targetPort: tls-port
    - name: follower-port
      port: 2888
      targetPort: follower-port
    - name: election-port
      port: 3888
      targetPort: election-port
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}