apiVersion: v1
kind: Service
metadata:
  name: pinpoint-web
  labels:
    {{- include "web.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: server-port
      port: 9997
      targetPort: server-port
      protocol: TCP
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}