apiVersion: v1
kind: Service
metadata:
  name: {{ include "xunlei.fullname" . }}
  labels:
    {{- include "xunlei.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "xunlei.selectorLabels" . | nindent 4 }}
