####################################################################
# 全局配置
####################################################################
# 维护状态
# 当进入维护状态时，hpa 将会失效，所有的 Deployment 和 StatefulSet 的 replicas 将被设置 0
maintenance: false

####################################################################
# Redis
# 目前只支持单实例
####################################################################
redis:
  image:
    repository: redis
    tag:
    pullPolicy: Always
  resources:
    limits:
      cpu: 2000m
      memory: 5Gi
  # 节点选择器
  nodeSelector: {}
  # 污点容忍度
  tolerations: []
  # 亲和性
  # 如果为空时，默认的亲和性规则如下:
  # 1. 必须将应用调度到与当前命名空间相同的节点上，保证生产环境和预发布环境节点隔离（节点需要提前打上标签 node.kubernetes.io/namespace=<namespace>）
  # 如果不为空时，以用户的亲和性为准
  affinity: {}
  # 修改 redis.conf
  # https://raw.githubusercontent.com/redis/redis/7.0/redis.conf
  conf:
    redis.conf: |
      maxmemory 4096mb
      maxmemory-policy allkeys-lru
      requirepass <redis-password>

####################################################################
# Redis Insight可视化界面
####################################################################
insight:
  # 是否部署 Redis Insight
  enabled: true
  image:
    repository: redislabs/redisinsight
    tag: 1.14.0
    pullPolicy: Always
  # 应用资源限制
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
  # 节点选择器
  nodeSelector: {}
  # 污点容忍度
  tolerations: []
  # 亲和性
  # 如果为空时，默认的亲和性规则如下:
  # 1. 必须将应用调度到与当前命名空间相同的节点上，保证生产环境和预发布环境节点隔离（节点需要提前打上标签 node.kubernetes.io/namespace=<namespace>）
  # 如果不为空时，以用户的亲和性为准
  affinity: {}
  ingress:
    className: "nginx"
    # 部署后，如果未指定 host，则 Redis 默认监听 redis.<namespace>.cluster.k8s
    #host: redis.cluster.k8s
  conf:
    # 受信任源
    # 这个需要设置为 RedisInsight 的外部访问地址，并且不能忽略协议。例:
    # https://redis.central-x.com
    trustedOrigins:
    # 应用子路径
    # RedisInsight 将会监听 <schema>://<domain><subpath> 路径
    subpath:
    # 动态子路径
    # RedisInsight 将会根据 dynamicSubpath 指定的请求头的值截取路径，这样 RedisInsight 就可以处理来自多个不同来源的代理的请求。例:
    # https://redis.central-x.com/tools/redisinsight/
    # https://redis.central-x.com/helpers/redisinsight/
    dynamicSubpath: X-Forwarded-Prefix