apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: redis-port
      port: 6379
      targetPort: socket
      protocol: TCP
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
